{
 "title": "Linkerd Top Line",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(request_total, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(request_total{deployment!=\"\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n    <a href=\"https://linkerd.io\" target=\"_blank\">Linkerd</a> is a next-generation ultralight service mesh for Kubernetes.\n    <br>\n    <span id=\"version\"></span>\n  </div>\n</div>\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/services/grafana:http/proxy/\"\n    )\n  )+'/services/web:http/proxy/overview';\nvar localReq = new XMLHttpRequest();\nlocalReq.responseType = \"document\";\nlocalReq.open('GET', localReqURL);\nlocalReq.onload = function() {\n  if (localReq.status === 200) {\n    var main = localReq.responseXML.getElementById('main');\n    var localVersion = main.getAttribute(\"data-release-version\");\n    var uuid = main.getAttribute(\"data-uuid\");\n\n    var versionElem = document.getElementById('version');\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.';\n\n    var versionReq = new XMLHttpRequest();\n    versionReq.responseType = 'json';\n    versionReq.open('GET', 'https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana');\n    versionReq.onload = function() {\n      if (versionReq.status === 200) {\n        var msg = \"\";\n        if (versionReq.response.version === localVersion) {\n          msg = ' Linkerd is up to date';\n        } else {\n          msg = \" A new version (\"+versionReq.response.version+\") is available. <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n        }\n        versionElem.innerHTML += msg;\n      }\n    };\n    versionReq.send();\n  }\n};\nlocalReq.send();\n</script>"
  },
  {
   "title": "GLOBAL SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=~\"$deployment\"}[30s])) / sum(irate(response_total{deployment=~\"$deployment\"}[30s]))"
    }
   ]
  },
  {
   "title": "GLOBAL REQUEST VOLUME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=~\"$deployment\"}[30s]))"
    }
   ]
  },
  {
   "title": "NAMESPACES MONITORED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=~\"$namespace\"}) by (namespace))"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS MONITORED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=~\"$namespace\"}) by (namespace, deployment))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 7 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP LINE</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9.2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=~\"$namespace\", direction=\"inbound\"}[30s])) by (namespace) / sum(irate(response_total{namespace=~\"$namespace\", direction=\"inbound\"}[30s])) by (namespace)",
     "legendFormat": "ns/{{namespace}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9.2 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", direction=\"inbound\", tls=\"true\"}[30s])) by (namespace)",
     "legendFormat": "🔒ns/{{namespace}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", direction=\"inbound\", tls!=\"true\"}[30s])) by (namespace)",
     "legendFormat": "ns/{{namespace}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9.2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=~\"$namespace\", direction=\"inbound\"}[30s])) by (le, namespace))",
     "legendFormat": "p95 ns/{{namespace}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 16.2 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>NAMESPACES</span>\n</div>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18.4 }, "repeat": "namespace" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19.4 },
   "content": "<div>\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <a href=\"./dashboard/db/linkerd-deployment?var-namespace=$namespace\">\n    <span style=\"font-size: 15px; border-image:none\">ns/$namespace</span>\n  </a>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21.4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21.4 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21.4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  }
 ]
}